// Copyright (C) 2026 StableLlama
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

/**
 * Defines the sourcebook list unit so this responsibility stays isolated, testable, and easy to evolve.
 */

import React, { useState, useEffect, useRef, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { AppTheme, SourcebookEntry } from '../../types';
import { useThemeClasses } from '../layout/ThemeContext';
import { listSourcebookEntries } from './sourcebookApi';
import {
  entryDiffSignature,
  filterSourcebookEntries,
  resolveExternalSourcebookEntries,
} from './sourcebookUtils';
import { SourcebookListView } from './SourcebookListView';
import { useSourcebookListMutations } from './useSourcebookListMutations';
import { useSourcebookEntryInteractions } from './hooks/useSourcebookEntryInteractions';
import { useSourcebookDialogLifecycle } from './hooks/useSourcebookDialogLifecycle';
import { useUIStore } from '../../stores/uiStore';

interface SourcebookListProps {
  theme?: AppTheme;
  externalEntries?: SourcebookEntry[];
  // ids currently checked by the relevance engine or user
  checkedIds?: string[];
  onToggle?: (id: string, checked: boolean) => void;
  isAutoSelectionEnabled?: boolean;
  isAutoSelectionRunning?: boolean;
  onToggleAutoSelection?: (enabled: boolean) => void;
  onMutated?: (entry: {
    label: string;
    onUndo?: () => Promise<void>;
    onRedo?: () => Promise<void>;
    entryId?: string;
    entryExistsInBaseline?: boolean;
    /** The upserted entry after create/update, or null after delete. */
    updatedEntry?: SourcebookEntry | null;
  }) => Promise<void>;
  mutatedEntryIds?: Set<string>;
  onAppUndo?: () => Promise<void>;
  onAppRedo?: () => Promise<void>;
  canAppUndo?: boolean;
  canAppRedo?: boolean;
  /** Trigger to open a specific entry via a mutation-tag click.  Uses an
   *  incrementing `id` so that clicking the same entry twice is always
   *  detected as a new click, even if the dialog was closed in between. */
  language?: string;
  baselineEntries?: SourcebookEntry[];
}

/**
 * Returns a canonical string signature for an entry so that two entry objects
 * with the same logical content are always equal even if optional array fields
 * differ between `undefined` and `[]`, or if elements are in a different order.
 * Used only for diff-indicator computations (not for display).
 *
 * IMPORTANT: Only include fields that are consistently present in BOTH data
 * sources (story-select endpoint and the sourcebook-list endpoint):
 *   - name, description, category, synonyms, images  ← always present
 *   - keywords  ← EXCLUDED: auto-generated by the backend, truncated
 *               differently by _normalize_entry_data vs the raw store, and
 *               never set directly by users or LLM tools.
 *   - relations ← EXCLUDED: stored in a separate `sourcebook_relations` list
 *               in story.json and therefore absent from the story-select
 *               response (history states).  The sourcebook-list endpoint
 *               re-injects them via _get_entry_relations(), so comparing
 *               with history baselines always produces a false positive.
 */
// Re-export utilities so existing importers of SourcebookList keep working.
export {
  filterSourcebookEntries,
  resolveExternalSourcebookEntries,
  updateSourcebookEntryInList,
} from './sourcebookUtils';

export const SourcebookList: React.FC<SourcebookListProps> = React.memo(
  ({
    theme = 'mixed',
    externalEntries,
    checkedIds = [],
    onToggle,
    isAutoSelectionEnabled = true,
    isAutoSelectionRunning = false,
    onToggleAutoSelection,
    onMutated,
    onAppUndo,
    onAppRedo,
    canAppUndo = false,
    canAppRedo = false,
    mutatedEntryIds,
    language = 'en',
    baselineEntries,
  }: SourcebookListProps) => {
    const { t } = useTranslation();
    const [entries, setEntries] = useState<SourcebookEntry[]>(
      resolveExternalSourcebookEntries(externalEntries, [])
    );
    const [search, setSearch] = useState('');
    const externalEntriesRef = useRef<SourcebookEntry[] | undefined>(undefined);
    const createdEntryIdsRef = useRef<Set<string>>(new Set());
    const [selectedEntry, setSelectedEntry] = useState<SourcebookEntry | null>(null);
    const [isDialogOpen, setIsDialogOpen] = useState(false);
    // Track whether the dialog was opened by a mutation-tag trigger (vs. a
    // manual list-item click).  Only when true can we safely show "new entry"
    // diff highlighting for entries that do not appear in the baseline.
    const [dialogOpenedViaTrigger, setDialogOpenedViaTrigger] = useState(false);
    // Incrementing this forces SourcebookEntryDialog to remount when the entry's
    // content changes externally (e.g. after app-level undo/redo), resetting all
    // dialog-local state (form fields, local history) cleanly.
    const [dialogKey, setDialogKey] = useState(0);

    const {
      isLoadingEntry,
      hoveredEntry,
      tooltipPos,
      availableImages,
      handleEntryHover,
      handleEntryHoverLeave,
      handleEntryClick,
      handleToggleEntry,
    } = useSourcebookEntryInteractions({
      isAutoSelectionEnabled,
      onToggle,
      createdEntryIdsRef,
      setEntries,
      setSelectedEntry,
      setDialogOpenedViaTrigger,
      setIsDialogOpen,
    });

    const { isLight } = useThemeClasses();

    const loadEntries = async (query?: string): Promise<void> => {
      try {
        const data = await listSourcebookEntries(query, 'extensive');
        setEntries(data);
      } catch (e) {
        console.error('Failed to load sourcebook', e);
      }
    };

    useEffect((): (() => void) => {
      let timeoutId: ReturnType<typeof setTimeout> | null = null;
      const hasQuery = search.trim().length > 0;

      // In embedded/external mode we still rely on backend search for non-empty
      // queries so filtering uses canonical sourcebook data (including generated keywords).
      if (Array.isArray(externalEntries) && !hasQuery) {
        const externalChanged = externalEntriesRef.current !== externalEntries;
        if (externalChanged) {
          externalEntriesRef.current = externalEntries;
          setEntries(filterSourcebookEntries(externalEntries, search));
        }
      } else {
        timeoutId = setTimeout((): void => {
          loadEntries(search);
        }, 300);
      }

      return (): void => {
        if (timeoutId) {
          clearTimeout(timeoutId);
        }
      };
    }, [externalEntries, search]);

    useSourcebookDialogLifecycle({
      entries,
      setEntries,
      setSelectedEntry,
      setDialogOpenedViaTrigger,
      setIsDialogOpen,
      externalEntries,
      isDialogOpen,
      selectedEntry,
      setDialogKey,
    });

    // Compute diff status for each entry relative to the baseline snapshot.
    const createdEntryIds = useMemo<Set<string>>((): Set<string> => {
      if (!baselineEntries) return new Set();
      const baselineIds = new Set(
        baselineEntries.map((b: SourcebookEntry): string => b.id)
      );
      return new Set(
        entries
          .filter((e: SourcebookEntry): boolean => !baselineIds.has(e.id))
          .map((e: SourcebookEntry): string => e.id)
      );
    }, [entries, baselineEntries]);

    useEffect((): void => {
      createdEntryIdsRef.current = createdEntryIds;
    }, [createdEntryIds]);

    const modifiedEntryIds = useMemo<Set<string>>((): Set<string> => {
      if (!baselineEntries) return new Set();
      return new Set(
        entries
          .filter((e: SourcebookEntry): boolean | undefined => {
            const baseline = baselineEntries.find(
              (b: SourcebookEntry): boolean => b.id === e.id
            );
            // Use entryDiffSignature to normalize optional arrays and field
            // ordering so that semantically identical entries stored at different
            // times (e.g. before and after an API refresh) are never falsely
            // flagged as modified.
            return baseline && entryDiffSignature(baseline) !== entryDiffSignature(e);
          })
          .map((e: SourcebookEntry): string => e.id)
      );
    }, [entries, baselineEntries]);
    const externalMutationEntryIds = mutatedEntryIds ?? new Set<string>();

    const deletedEntries = useMemo<SourcebookEntry[]>((): SourcebookEntry[] => {
      if (!baselineEntries) return [];
      const currentIds = new Set(entries.map((e: SourcebookEntry): string => e.id));
      return baselineEntries.filter(
        (b: SourcebookEntry): boolean => !currentIds.has(b.id)
      );
    }, [entries, baselineEntries]);

    const { handleCreate, handleUpdate, handleDelete } = useSourcebookListMutations({
      entries,
      selectedEntry,
      setEntries,
      setSelectedEntry,
      externalEntries,
      search,
      baselineEntries,
      onMutated,
      loadEntries,
    });

    const borderClass = isLight ? 'border-brand-gray-200' : 'border-brand-gray-800';
    const textHeaderClass = isLight ? 'text-brand-gray-500' : 'text-brand-gray-400';
    const textClass = isLight ? 'text-brand-gray-900' : 'text-brand-gray-200';
    const subTextClass = isLight ? 'text-brand-gray-500' : 'text-brand-gray-400';
    const itemHoverClass = isLight
      ? 'hover:bg-brand-gray-100'
      : 'hover:bg-brand-gray-800';
    const inputBg = isLight ? 'bg-white' : 'bg-brand-gray-950/50';
    const inputBorder = isLight ? 'border-brand-gray-200' : 'border-brand-gray-800';
    const inputPlace = 'placeholder-brand-gray-500';
    const btnHover = isLight
      ? 'hover:bg-brand-gray-200 text-brand-gray-500 hover:text-brand-gray-700'
      : 'hover:bg-brand-gray-800 text-brand-gray-500 hover:text-brand-gray-300';

    return (
      <SourcebookListView
        theme={theme}
        language={language}
        t={t}
        entries={entries}
        checkedIds={checkedIds}
        search={search}
        selectedEntry={selectedEntry}
        isDialogOpen={isDialogOpen}
        isLoadingEntry={isLoadingEntry}
        isAutoSelectionEnabled={isAutoSelectionEnabled}
        isAutoSelectionRunning={isAutoSelectionRunning}
        dialogKey={dialogKey}
        dialogOpenedViaTrigger={dialogOpenedViaTrigger}
        hoveredEntry={hoveredEntry}
        tooltipPos={tooltipPos}
        availableImages={availableImages}
        createdEntryIds={createdEntryIds}
        modifiedEntryIds={modifiedEntryIds}
        externalMutationEntryIds={externalMutationEntryIds}
        deletedEntries={deletedEntries}
        baselineEntries={baselineEntries}
        canAppUndo={canAppUndo}
        canAppRedo={canAppRedo}
        onAppUndo={onAppUndo}
        onAppRedo={onAppRedo}
        onToggleAutoSelection={onToggleAutoSelection}
        onSearchChange={setSearch}
        onOpenCreate={(): void => {
          setSelectedEntry(null);
          setIsDialogOpen(true);
        }}
        onDialogClose={(): void => {
          setIsDialogOpen(false);
          setDialogOpenedViaTrigger(false);
          useUIStore.getState().closeSourcebookDialog();
        }}
        onEntryClick={handleEntryClick}
        onEntryHover={handleEntryHover}
        onEntryHoverLeave={handleEntryHoverLeave}
        onToggleEntry={handleToggleEntry}
        onSaveCreate={handleCreate}
        onSaveUpdate={handleUpdate}
        onDeleteEntry={handleDelete}
        isLight={isLight}
        borderClass={borderClass}
        textClass={textClass}
        textHeaderClass={textHeaderClass}
        subTextClass={subTextClass}
        itemHoverClass={itemHoverClass}
        inputBg={inputBg}
        inputBorder={inputBorder}
        inputPlace={inputPlace}
        btnHover={btnHover}
      />
    );
  }
);

SourcebookList.displayName = 'SourcebookList';
