// Copyright (C) 2026 StableLlama
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

/**
 * Purpose: Generate TypeScript types from the backend OpenAPI schema.
 *
 * Usage (from src/frontend/):
 *   node scripts/generateTypes.mjs
 *
 * What this script does:
 *   1. Runs openapi-typescript to generate raw types from ../../openapi.json
 *   2. Prepends the GPL licence header + Purpose comment required by this repo's
 *      code-hygiene rules.
 *
 * The output file (types/api.generated.ts) is committed to version control so
 * that the rest of the frontend can import from it without running code
 * generation on every build. Regenerate whenever backend models change.
 */

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const frontendRoot = resolve(__dirname, '..');
const schemaPath = resolve(frontendRoot, '../../openapi.json');
const outputPath = resolve(frontendRoot, 'types/api.generated.ts');

const GPL_HEADER = `// Copyright (C) 2026 StableLlama
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

/**
 * Purpose: Auto-generated TypeScript types derived from the backend OpenAPI schema.
 *
 * DO NOT EDIT THIS FILE MANUALLY. Regenerate by running:
 *   python tools/export_openapi.py   (from repo root, with venv active)
 *   cd src/frontend && npm run generate:types
 *
 * Consumers: import { components, operations, paths } from '../types/api.generated';
 * Access schema types via: components['schemas']['SomeModel']
 */

`;

// Step 1: run openapi-typescript to generate raw output
console.log(`Generating types from ${schemaPath} …`);
execSync(`npx openapi-typescript "${schemaPath}" -o "${outputPath}"`, {
  stdio: 'inherit',
  cwd: frontendRoot,
});

// Step 2: prepend GPL header (the tool writes its own banner first; replace it)
const generated = readFileSync(outputPath, 'utf-8');
// Strip the one-line auto-generated comment the tool writes
const withoutToolBanner = generated.replace(
  /^\/\*\*\n \* This file was auto-generated by openapi-typescript\.\n \* Do not make direct changes to the file\.\n \*\/\n/,
  ''
);
writeFileSync(outputPath, GPL_HEADER + withoutToolBanner, 'utf-8');
console.log(`Formatting generated types with Prettier…`);
execSync(`npx prettier --write ${JSON.stringify(outputPath)}`, {
  stdio: 'inherit',
  cwd: frontendRoot,
});
console.log(`Types written to ${outputPath}`);
